version: '2.1'
services:
  api-test:
    container_name: twitter_test_api_java
    build:
      context: ./../
      dockerfile: ./Docker/jdk/Dockerfile
    env_file:
      - ./env.conf
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./../:/code
      - ./build/allure-results:/app/allure-results
    entrypoint: ./Docker/entrypoint.sh
